#!/bin/sh
case "${DEVICENAME:-}" in zt*) ;; *) exit 0 ;; esac
case "${ACTION:-}" in
	add) /usr/libexec/zerotier-f50-firewall refresh ;;
	remove) /usr/libexec/zerotier-f50-firewall refresh "$DEVICENAME" ;;
	*) exit 0 ;;
esac
